FROM debian:trixie-slim

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers

ARG LOCALE=en_US.UTF-8

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV TZ=UTC

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        locales \
    && echo "${LOCALE} UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=${LOCALE}
ENV LC_ALL=${LOCALE}
