FROM ghcr.io/christoffercarlsson/debian:latest

ARG RUST_VERSION=1.98.1

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        rustup \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN rustup set profile minimal \
    && rustup toolchain install ${RUST_VERSION} \
    && rustup default ${RUST_VERSION}

RUN rustc --version \
    && cargo --version

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
