FROM restic/rest-server:latest

ENV OPTIONS="--append-only --private-repos"
ENV DATA_DIRECTORY /data
ENV PASSWORD_FILE /htpasswd

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
