FROM node:lts-trixie-slim AS builder

RUN npm install -g pnpm

FROM ghcr.io/christoffercarlsson/debian:latest

RUN groupadd --gid 1000 node \
    && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=builder /usr/local/bin /usr/local/bin
RUN rm /usr/local/bin/yarn \
    /usr/local/bin/yarnpkg \
    /usr/local/bin/docker-entrypoint.sh \
    /usr/local/bin/nodejs

RUN node --version \
    && npm --version \
    && pnpm --version

ENTRYPOINT ["node"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
