FROM node:lts-trixie-slim AS builder

RUN npm install -g pnpm

FROM ghcr.io/christoffercarlsson/debian:latest

COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=builder /usr/local/bin /usr/local/bin
RUN rm /usr/local/bin/yarn \
    /usr/local/bin/yarnpkg \
    /usr/local/bin/docker-entrypoint.sh \
    /usr/local/bin/nodejs

RUN node --version \
    && npm --version \
    && pnpm --version

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
